import SwiftUI
import PDFKit

@MainActor
class PDFManager {
    static let shared = PDFManager()
    
    private init() {}
    
    func generatePDF(from note: SermonNote) -> URL? {
        let renderer = ImageRenderer(content: NotePDFView(note: note))
        
        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent("\(note.title.replacingOccurrences(of: " ", with: "_")).pdf")
        
        renderer.render { size, context in
            var box = CGRect(origin: .zero, size: size)
            
            guard let pdfContext = CGContext(tempURL as CFURL, mediaBox: &box, nil) else { return }
            
            pdfContext.beginPDFPage(nil)
            context(pdfContext)
            pdfContext.endPDFPage()
            pdfContext.closePDF()
        }
        
        return tempURL
    }
}

private struct NotePDFView: View {
    let note: SermonNote
    
    var body: some View {
        VStack(alignment: .leading, spacing: 20) {
            Text("Sermon Flow")
                .font(.custom("Georgia", size: 12))
                .foregroundColor(.gray)
            
            Text(note.title)
                .font(.custom("Georgia", size: 32).bold())
                .foregroundColor(Color(red: 0.18, green: 0.18, blue: 0.18))
            
            if let series = note.seriesTitle {
                Text("Series: \(series)")
                    .font(.custom("Georgia", size: 16).italic())
                    .foregroundColor(Color(red: 0.83, green: 0.69, blue: 0.22))
            }
            
            Text(note.timestamp, format: .dateTime.month().day().year())
                .font(.custom("Georgia", size: 14))
                .foregroundColor(.gray)
            
            Divider()
            
            Text(note.body)
                .font(.custom("Georgia", size: 18))
                .lineSpacing(6)
                .foregroundColor(Color(red: 0.18, green: 0.18, blue: 0.18))
            
            if note.isLifeApplication {
                VStack(alignment: .leading, spacing: 10) {
                    Divider()
                    Text("Life Application")
                        .font(.custom("Georgia", size: 16).bold())
                        .foregroundColor(Color(red: 0.83, green: 0.69, blue: 0.22))
                    Text("This note was marked for practical application.")
                        .font(.custom("Georgia", size: 14).italic())
                }
                .padding(.top, 20)
            }
            
            Spacer()
            
            Text("Generated by Sermon Flow")
                .font(.caption)
                .foregroundColor(.gray)
                .frame(maxWidth: .infinity, alignment: .center)
        }
        .padding(60)
        .frame(width: 612, height: 792) // Standard US Letter size
        .background(Color(red: 0.96, green: 0.96, blue: 0.86))
    }
}
